abstract class CountMoneyAppRigesterStates {}

class IntialCountMoneyAppRigesterStates extends CountMoneyAppRigesterStates {}
class CountMoneyAppLoadingRigesterStates extends CountMoneyAppRigesterStates {}
class CountMoneyAppScuccessRigesterStates extends CountMoneyAppRigesterStates {}
class CountMoneyAppErrorRigesterStates extends CountMoneyAppRigesterStates {}



class CountMoneyAppLoadingCreateUsersStates extends CountMoneyAppRigesterStates {}
class CountMoneyAppSucessCreateUsersStates extends CountMoneyAppRigesterStates {}
class CountMoneyAppErrorCreateUsersStates extends CountMoneyAppRigesterStates {}



class CountMoneyChangPasswordVisabilityRigesterStates extends CountMoneyAppRigesterStates {}